webtalk_init -webtalk_dir C:/Users/Yankey/Desktop/Projects/MemoryStudies/Instruction_Buffer/Instruction_Buffer.sim/sim_1/behav/xsim/xsim.dir/IBuff_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jun  3 11:19:40 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f674e838-9ba3-4997-9f0e-2a5b2bc0926f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4b0a00863f34449fab695dad198dee26" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3921900 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13956_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2561754868 -regid "" -xml C:/Users/Yankey/Desktop/Projects/MemoryStudies/Instruction_Buffer/Instruction_Buffer.sim/sim_1/behav/xsim/xsim.dir/IBuff_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Yankey/Desktop/Projects/MemoryStudies/Instruction_Buffer/Instruction_Buffer.sim/sim_1/behav/xsim/xsim.dir/IBuff_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Yankey/Desktop/Projects/MemoryStudies/Instruction_Buffer/Instruction_Buffer.sim/sim_1/behav/xsim/xsim.dir/IBuff_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
